Repository archethic-foundation/libjs, pull requests merged in 2022-05, with the labels that each got.

#44 Add origin key API
  README.md
  build.js
  dist/index.js
  dist/index.js.map
  esbuild.inject.js
  example/keychain.html
  example/transactionBuilder.html
  index.js
  lib/api.js
  lib/utils.js
  package-lock.json
  package.json
  webpack.config.js
Labels: feature, breaking-change

#49 Add transaction building from the keychain
  README.md
  dist/index.js
  dist/index.js.map
  example/keychain.html
  lib/api.js
  lib/keychain.js
  test/keychain.js
Labels: feature

#50 add method #47setOrginSignature
  README.md
  lib/transaction_builder.js
Labels: feature

#51 Rework readme
  README.md
Labels: documentation

#52 Fix Keychain DID document to be conform
  dist/index.js
  dist/index.js.map
  lib/keychain.js
  test/keychain.js
Labels: bug
