Repository archethic-foundation/libjs, pull requests merged in 2022-06, with the labels that each got.

#57 Managing origin key
  README.md
  dist/index.js
  dist/index.js.map
  example/keychain.html
  example/transactionBuilder.html
  index.js
  lib/api.js
  lib/utils.js
Labels: breaking-change

#59 Add token id
  dist/index.js
  dist/index.js.map
  example/transactionBuilder.html
  lib/transaction_builder.js
  test/transaction_builder.js
Labels: feature

#61 Support WebSocket Secure (wss) for waitConfirmations call
  lib/api.js
Labels: bug
