Repository archethic-foundation/libjs, pull requests merged in 2024-06, with the labels that each got.

#198 feat(keychain): add toJSON() method to Keychain class
  src/keychain.ts
  tests/keychain.test.ts
Labels: feature, external-contribution

#181 🚧 Add WebChannel RPC transport layer.
  example/rpcCurrentAccount/app.js
  example/rpcCurrentAccount/index.html
  example/rpcCurrentAccount/package-lock.json
  package-lock.json
  package.json
  src/api/wallet_rpc.browserextension.ts
  src/api/wallet_rpc.ts
  src/api/wallet_rpc.websocket.ts
  src/endpoint.ts
  src/index.ts
  tests/endpoint.test.ts
  tests/index.test.ts
Labels: feature

#196 feat(crypto): Add encryption functionality
  package-lock.json
  package.json
  src/crypto.ts
  tests/crypto.test.ts
Labels: feature, external-contribution

#213 Add function to deploy contract
  README.md
  example/contractDeployer/app.js
  example/contractDeployer/build.js
  example/contractDeployer/index.html
  example/contractDeployer/package-lock.json
  example/contractDeployer/package.json
  example/transactionBuilder/app.js
  src/contract.ts
Labels: feature

#197 fix(toBigInt): refactor function and improve tests
  README.md
  example/keychain/app.js
  example/rpcDeriveKeypairAddress/app.js
  example/rpcService/app.js
  example/rpcTransactionBuilder/app.js
  example/transactionBuilder/app.js
  example/transactionBuilder/package-lock.json
  package-lock.json
  package.json
  src/crypto.ts
  src/keychain.ts
  src/transaction_builder.ts
  src/typed_encoding.ts
  src/types.ts
  src/utils.ts
  src/varint.ts
  tests/account.test.ts
  tests/keychain.test.ts
  tests/network.test.ts
  tests/transaction_builder.test.ts
  tests/typed_encoding.test.ts
  tests/utils.test.ts
  tests/varint.test.ts
Labels: bug, external-contribution
